### ISSUE TITLE
define the main camu package intro patch

### ISSUE THREAD

**Issue by diemoschwarz** [Ircam-RnD/catart-mubu#59]
### Tabs
- [x] intro: working simple catart
- [x] example full patches
   - catart-simple
   - catart-mfcc-pca
- [x] abstractions
- [x] tutorials
- [x] ~~advanced patches~~ -> together with (the few) full patches
   - catoracle
   - catart-spat
   - catart-som

**Comment by diemoschwarz** [comment]
what to choose as *Intro: a working minimal catart patch*? I have a penchant for the simplest one `catart-mubu-tutorial 1a selection` (lower left).  Alternatively, the foremost tab could be directly the list of main patches.
![Screenshot 2023-01-04 at 15 04 54](https://user-images.githubusercontent.com/378151/210572427-02f35a49-7781-4d71-8f63-4aa73f7f61c0.png)

**Comment by christophertrapani** [comment]
Lower left makes sense to me, after a quick glance.COn Jan 4, 2023, at 7:39 PM, diemo ***@***.***> wrote:﻿
what to choose as Intro: a working minimal catart patch? I have a penchant for the simplest one catart-mubu-tutorial 1a selection (lower left).  Alternatively, the foremost tab could be directly the list of main patches.

**Comment by diemoschwarz** [comment]
All tabs are complete now. Can you take a quick look to see if this catart package entry patch is inviting and clear enough?

**Comment by diemoschwarz** [comment]
### Todos from Zoom Meeting AE, CT, DS:

- [ ] add coloured groups
- [ ] add logo
- [ ] hide details
- [ ] hide default load
- [ ] show descr. values
- [ ] zoom out x after reload

**Comment by diemoschwarz** [comment]
- [ ] add credits. Suggestion:
> Developed at IRCAM by the ISMM team and contributors: Diemo Schwarz, Aaron Einbond, Christopher Trapani, and others. Based on MuBu for Max by Norbert Schnell, Riccardo Borghesi, Diemo Schwarz and the ISMM team.

**Comment by christophertrapani** [comment]
Looks good!On Mar 29, 2023, at 1:34 PM, diemo ***@***.***> wrote:﻿

 add credits. Suggestion:


Developed at IRCAM by the ISMM team and contributors: Diemo Schwarz, Aaron Einbond, Christopher Trapani, and others. Based on MuBu for Max by Norbert Schnell, Riccardo Borghesi, Diemo Schwarz and the ISMM team.
